### ISSUE TITLE
Needs clearer installation instructions

### ISSUE THREAD

**Issue by uptudev** [rshkarin/mason-nvim-lint#11]
Lazy.nvim is the standard, and installing this plugin as written does nothing but throw a warning on startup that none of the linters configured are in mason's registry.

Odds are this is due to a loading order error, so perhaps clear instructions should be given in the README on how to resolve it, as setting them to not lazy load with `lazy = false` and setting up dependencies does nothing.

**Comment by uptudev** [comment]
Error message:
![image](https://github.com/rshkarin/mason-nvim-lint/assets/91502176/8e4fcfc5-01bd-42e6-8c81-af8f7cdcc197)

Mason:
![image](https://github.com/rshkarin/mason-nvim-lint/assets/91502176/3e01674e-2720-497c-9aa1-aab8dbd164e5)

Lazy.nvim mason declaration (line 93):
```lua
{
      'williamboman/mason.nvim',
      lazy = false,
      config = function()
        require('mason').setup({
          ui = {
            icons = {
              package_installed = "",
              package_pending = "",
              package_uninstalled = "",
            },
          }
        })
      end,
  },

```

Lazy.nvim nvim-lint declaration (line 140):
```lua
{
    'mfussenegger/nvim-lint',
    dependencies = 'williamboman/mason.nvim',
    lazy = false,
    config = function()
      require('lint').linters_by_ft = {
        rust = {"bacon"},
        lua = {'luacheck'},
        javascript = {'eslint'},
        typescript = {'eslint'},
        typescriptreact = {'eslint'},
        html = {'htmlhint'},
        css = {'stylelint'},
        scss = {'stylelint'},
        sass = {'stylelint'},
        less = {'stylelint'},
        json = {'jsonlint'},
        yaml = {'yamllint'},
        markdown = {'vale'},
        sh = {'shellcheck'},
      }
    end
  },
```

Lazy.nvim mason-nvim-lint declaration (line 225):
```lua
  {
    'rshkarin/mason-nvim-lint',
    lazy = false,
    dependencies = {
        'williamboman/mason.nvim',
        'mfussenegger/nvim-lint',
    },
    config = function()
      require('mason-nvim-lint').setup()
    end,
  },
```

**Comment by rshkarin** [comment]
@uptudev to resolve the issue, you need to remove bacon from `nvim-lint` and add it to the `ensure_installed` list in `mason-nvim-lint`. This change is necessary because bacon is not supported by `nvim-lint` and therefore cannot be installed automatically through its configuration. Regarding `htmlhint`, it was missed in the mapping, as was recently added, I have updated the mappings, so it should now work correctly:

```
 {
    'rshkarin/mason-nvim-lint',
    dependencies = {
        'williamboman/mason.nvim',
        'mfussenegger/nvim-lint',
    },
    config = function()
        require("mason-nvim-lint").setup({
            ensure_installed = {'bacon', 'htmlhint', 'eslint'},
        })
    end
}
  ```

**Comment by uptudev** [comment]
Apologies; I had forgotten about this issue until I saw it when looking for another one.

This did indeed resolve the issue. Thank you very much for your help.
