### ISSUE TITLE
Add setting to ignore linters

### ISSUE THREAD

**Issue by primeapple** [rshkarin/mason-nvim-lint#5]
In my `nvim-lint` setup I have a linter for fish set up:

```
        lint.linters_by_ft = {
            fish = { 'fish' },
		}
```

Now fish doesn't need a separate linter to be installed, it has the linter in it's executable. However, this plugin detects fish and tries to install it, failing with:
> Linters [fish] are absent in the mason's registry. Please, install them manually and remove from configuration.                                                                                                                              

It would be nice to have an option to ignore certain linters.

**Comment by LeonardoMor** [comment]
This would be nice to have!
