### ISSUE TITLE
keep showing installed write_good linter.

### ISSUE THREAD

**Issue by cxwx** [rshkarin/mason-nvim-lint#7]
  Warn  02:16:38 notify.warn Linters [write_good] are absent in the mason's registry. Please, install them manually and remove from configuration.
 
 but I've install the write-good with Mason.
 the message was caused by `mason-nvim-lint`

**Comment by rshkarin** [comment]
@cxwx mapping for `write-good` was added, so you can specify it in your `nvim-lint` as `write_good`.
